### PR TITLE
Python update

### PR DESCRIPTION
**Pull request by LowellPeltier**
I've completed the re-writes of all of the source python modules; Driver.py, ssimTools.py, and GiMeObj.py. The GiMeObj changes are the most significant, rebuilding the structure entirely. It now operates on a class instance structure based around "Obj" class objects. This will allow greater modularity, making it simple to simulate disparate populations at the same time without needing to alter the fundamental structure of the module as was needed to be done in the past. This structure  is also intended to improve the clarity of the GiMeObj module, allowing others to more easily modify GiMeObj and utilize the survey simulator.

I've provided four example GIMeObj modules, that should serve as basic templates for the types of modules other would wish to create. They are intended to serve as starting points for modification into functional versions for others to use.

I've re-written the README file to explain these changes, the list of files now included, and the operation of the python wrapper.

I've also migrated the python code back into the Python folder, removing the need for the Lawler folder. 

Work that still needs to be done:
The proper method for compilation of the fortran source code still needs to be determined, and instructions for how this will be accomplished will need to be written. This requires further testing and discussion before it can be implemented.

The python wrapper is currently operating using an older version of the fortran source code, but the up-to-date version doesn't seem to compile in expected ways. Work should be done to accomplish compatibility between the python wrapper and the most up to date fortran source code, but this will require coordination with others.

### CODE REVIEW

**Comment by mtbannister** [comment]
Hi @LowellPeltier, this is great to see. Where are the tests that you've built for this major upgrade?

**Comment by LowellPeltier** [comment]
> Hi @LowellPeltier, this is great to see. Where are the tests that you've built for this major upgrade?

Hello @mtbannister,

Putting unit tests into the code was discussed, but ultimately @samlawler and I were uncertain how useful such things would be. This is for a few reasons. 

First, the random nature of much of GiMeObj makes such things difficult to implement. Even if properly setup and seeded, when executed if two unrelated lines of code, both invoking the random number generator, were to be switched in order having no effect on the actual execution of the program, the unit tests would fail. (The original version of the code was using two separate random number generators, one of which wasn't being seeded by the user, further compounding this issue.)

Secondly, it is the nature of GiMeObj to be heavily customized by the user. There are no tests I could define that would apply to the numerous use cases devised by the people to use the module. Again, even if they were using my code exactly and only rearranged a few lines, the tests would fail. 

As for things like Driver or ssimTools, my changes are more cosmetic as opposed to a functional re-write. They did not have test before, and I'm not sure of their value now. ssimTools is largely file input/output, so I'm not sure testing is necessary. Driver on the other hand is mainly used to call other programs, whose returns will vary between calls. Perhaps it is my inexperience with unit tests, but I'm uncertain how I could implement such things here.


Within GiMeObj, while it is not a unit test, I have implemented a plotting method that can be easily used as a diagnostic test of the generated distributions. This serves a dual purpose, it allows the user to verify that the generation methods they used are functioning correctly, and it also allows them to see that the distributions are behaving exactly as they expect scientifically. 

Personally, I found them extremely helpful in the designing of the module, and in setting up the examples. I could quickly visually identify if the distribution methods were functioning as intended, but also that the values generated were those I expected. I was able to pick out some fringe cases and other unexpected behavior in the way the distributions were written. I was also able to pick out odd statistical effects when certain values were chosen for some distributions.

I acknowledge these aren't tests per se, but they function in a similar manner and encourage users to carefully consider the distributions they've generated. If however you feel that more traditional unit tests need to be created, with a little guidance I'm certain I could get that done.

**Comment by jmpetit** [comment]
Hi there,

I just became aware of this project very recently. I didn't know you wanted to create a pipy distribution of the survey simulator. That sounds like a good idea. Does this mean you'll have to rewrite the whole thing in Python, or can you keep the survey simulator itself in Fortran (there exist a F95 version which is now the active one) and only rewrite the driver and GiMeObj ?

For GiMeObj, this is supposed to be supplied by the user, and depends heavily on the model one wants to implement. The only generic version is ReadModelFromFile.f95.

If going for a large distribution the survey simulator, I guess we should try and parallelize the the core of the program, the Detos1 routine. We can do this in the driver which would launch multiple instances of Detos1, likely with multiple MPI threads, or using somethink like the multiprocessing module from python. In this case, we need to feed each instance of Detos1 with many objects so it spends some time churning the number before being caught in the administration overhead. An other way to parallelize is to feed Detos1 with many objects at once, and then make it run in parallel with some OpenMP mechanism or other multithreading inside Detos1. Whether one should paralellize with respect to objects or surveys remains to be seen.

I've seen there are 2 issues open. I'll give some info on each of them directly in the individual threads.

Cheers, Jean-Marc

**Comment by ijiraq** [comment]
Going with pyPI does not require moving to python only code.  We have fortran code that is part of the pyPI distribution and compile that during install.

**Comment by cshankm** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I'm happy to see the Python wrapper/implementation of the survey simulator live on! The python wrapper and tools I was using were definitely slower in the runtime testing I did, but the flexibility and ease of configuring different models to test in python more than made up for that for me.                                                                                                                                        Cory                                                                                                                                                                                 From: notifications@github.comSent: March 13, 2020 10:00 AMTo: SurveySimulator@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: Re: [OSSOS/SurveySimulator] Python update (#5)  
Hi there,
I just became aware of this project very recently. I didn't know you wanted to create a pipy distribution of the survey simulator. That sounds like a good idea. Does this mean you'll have to rewrite the whole thing in Python, or can you keep the survey simulator itself in Fortran (there exist a F95 version which is now the active one) and only rewrite the driver and GiMeObj ?
For GiMeObj, this is supposed to be supplied by the user, and depends heavily on the model one wants to implement. The only generic version is ReadModelFromFile.f95.
If going for a large distribution the survey simulator, I guess we should try and parallelize the the core of the program, the Detos1 routine. We can do this in the driver which would launch multiple instances of Detos1, likely with multiple MPI threads, or using somethink like the multiprocessing module from python. In this case, we need to feed each instance of Detos1 with many objects so it spends some time churning the number before being caught in the administration overhead. An other way to parallelize is to feed Detos1 with many objects at once, and then make it run in parallel with some OpenMP mechanism or other multithreading inside Detos1. Whether one should paralellize with respect to objects or surveys remains to be seen.
I've seen there are 2 issues open. I'll give some info on each of them directly in the individual threads.
Cheers, Jean-Marc

**Comment by LowellPeltier** [comment]
It is my understanding that trying to run the entire survey simulator using python is much too slow to be of use. However, I'm not sure how much effort has been expended investigating this in the past. Python generally has a reputation for being pretty slow. 

As for the PyPI package, It shouldn't be a problem to have the core files written in fortran. Rebound for example is a Package that runs using C code and is available through PIP. In our specific case with fortran I'm not sure of exactly what will be required to accomplish this, but I don;t see a reason why it can't be done. As it stands how we will compile and use the fortran is a question I don't have a good answer to. The .so files created by F2PY are not portable between systems as far as I'm aware, but this is well outside my bailiwick my background is physics not computer science. Worst case scenario rather than providing something already compiled that can be used immediately, we provide the source files and instructions or some code to compile the fortran on the user's system.

Currently this python code is operating off of an older F77 implementation of the survey simulator. I saw the updates made to the source code in the repository, but I wasn't able to get them to compile using F2PY. Instead Sam provided me with the working version she had been using. Looking at the F2PY documentation I remember there being some idiosyncrasies compiling F95 files, perhaps that's what the problem was. 

You are correct that GiMeObj is intended to be created by the user, but the python module supplied here is more of a template for how that would be accomplished. By implementing a class structure for object populations this allows a lot of versatility and modularity in designing a GiMeObj file. However this structure is somewhat different to the usual procedural programming done by many scientists. It's certainly possible for users to design their own version completely from scratch, but I'm hoping this can reduce the learning curve, allowing them to skip most of the computer science and jump right into survey simulation.

As for parallelization, it's not something I have experience with but I can do some research on it. I believe it could be accomplished either through the python Driver, or within the fortran itself. Both would be viable, but other's experience may inform which is the better approach.

**Comment by cshankm** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  I haven't looked at or kept up with this stuff in years, so I don't know the current state of the survey simulator or anything like that. But what I was doing a few years ago, which I think is what you're building off of Lowell is:Compiling f2py on my machine and/or virtual machine for cluster deployment. I provided instructions for how others could do that if they wanted to use the python wrapper. And I only used the most basic paralellization where you run independent jobs on different clusters and assemble later. Stupidly simple paralellization, but it gets the job done. Won't take advantage of GPU clusters or similar though. And I haven't seen your updates to the python gimiobj, but that's exactly the approach I was taking as well. Providing. A set of tools to sample Hmag, inclination and other distributions. I didn't get as far as building tools to model resonance or other populations, but I think that's definitely the next step. For the simulations I was running, I found the cluster approach to be fast enough. Though maybe some of the populations you folks are modelling now are more computationally intensive. Cory                                                                                                                                                                                                                                                                                                                        From: notifications@github.comSent: March 13, 2020 11:15 AMTo: SurveySimulator@noreply.github.comReply-to: reply@reply.github.comCc: cshankm@gmail.com; comment@noreply.github.comSubject: Re: [OSSOS/SurveySimulator] Python update (#5)  
It is my understanding that trying to run the entire survey simulator using python is much too slow to be of use. However, I'm not sure how much effort has been expended investigating this in the past. Python generally has a reputation for being pretty slow.
As for the PyPI package, It shouldn't be a problem to have the core files written in fortran. Rebound for example is a Package that runs using C code and is available through PIP. In our specific case with fortran I'm not sure of exactly what will be required to accomplish this, but I don;t see a reason why it can't be done. As it stands how we will compile and use the fortran is a question I don't have a good answer to. The .so files created by F2PY are not portable between systems as far as I'm aware, but this is well outside my bailiwick my background is physics not computer science. Worst case scenario rather than providing something already compiled that can be used immediately, we provide the source files and instructions or some code to compile the fortran on the user's system.
Currently this python code is operating off of an older F77 implementation of the survey simulator. I saw the updates made to the source code in the repository, but I wasn't able to get them to compile using F2PY. Instead Sam provided me with the working version she had been using. Looking at the F2PY documentation I remember there being some idiosyncrasies compiling F95 files, perhaps that's what the problem was.
You are correct that GiMeObj is intended to be created by the user, but the python module supplied here is more of a template for how that would be accomplished. By implementing a class structure for object populations this allows a lot of versatility and modularity in designing a GiMeObj file. However this structure is somewhat different to the usual procedural programming done by many scientists. It's certainly possible for users to design their own version completely from scratch, but I'm hoping this can reduce the learning curve, allowing them to skip most of the computer science and jump right into survey simulation.
As for parallelization, it's not something I have experience with but I can do some research on it. I believe it could be accomplished either through the python Driver, or within the fortran itself. Both would be viable, but other's experience may inform which is the better approach.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by LowellPeltier** [comment]
> I'm having trouble with the code review interface right now. I'll add more comments once I solve my technical problem.
> 
> If you want to create executable use the entry points section of setup.py instead. Putting bin/env in here is bound to cause problems in future.
> Also, keep you entry_points clean.
> `https://setuptools.readthedocs.io/en/latest/setuptools.html`

The Shebang at the top of Driver wasn't actually being used, I think I just forgot to remove it during the code reorganization.

**Comment by samlawler** [comment]
Hi everyone!

Let me just re-iterate that what we've tried to do here (and by "we," I mean Lowell since he did all the work) is make a version of the Survey Simulator that is easy for someone outside OSSOS to download and work.  What we're hoping to get from all of you experts taking a look at the improved version is:
1) Anything that we've missed in the python wrapper or anything that needs to be explained better to a non-OSSOS person
2) Help and suggestions for getting the fortran core of the code to work on multiple different systems - we've only been able to test it with Ubuntu because that's what we have.

If anyone thinks this discussion would be better served with a telecon, let me know and I'll set one up for the next couple of weeks.

**Comment by ijiraq** [comment]
I also don't want to stifle this great interaction that has started.  But suggest that the pull request thread is the wrong place for this.  A standard issue would be a better place.   Otherwise it will be impossible for Lowell to get his requested changes accepted.  So, in this thread, please only review the code and post code review comments. 

BTW:  'where are the tests' is a totally valid question at the code review level.

**Comment by mtbannister** [comment]
Thanks @LowellPeltier, that satisfies my thoughts on the addition of unit tests.

**Comment by samlawler** [comment]
Hi OSSOS coders,  I know everything in the world has gotten completely crazy since Lowell submitted his pull request.  So, this is just a gentle nudge to ask if there is anything lacking in his code that must be remedied before it's useable by the wider community?  I just want to make sure that his hard work on this over the last few weeks isn't lost.  Hope you are all staying healthy!

**Pull request merged**
